from .entity import Entity
from .user import User
from .mahasiswa import Mahasiswa
from .donatur import Donatur
from .donatur_individual import DonaturIndividual
from .donatur_yayasan import DonaturYayasan
from .skema_beasiswa import SkemaBeasiswa
from .skema_beasiswa_aktif import SkemaBeasiswaAktif
from .pendaftaran import Pendaftaran
