version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout     
     
     # login to heroku docker registry
     - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

     # deploy the image
     - run: docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest

 deploy:
   branches: 
     only: 
       - master
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build --rm=false -t registry.heroku.com/$HEROKU_APP_NAME/web .

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
