version: 2
jobs:
 build_and_deploy:
   machine: true
   steps:
     - checkout
     
     ### deploy to HEROKU
     
     # login to heroku docker registry
     - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

     # build the application image
     - run: docker build --rm=false -t registry.heroku.com/$HEROKU_APP_NAME/web .

     # deploy the image to heroku
     - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest; fi

     # deploy to enau.cs.ui.ac.id
     - run: >
        if [ "master" == "master" ]; then
          tar -czvf ${CIRCLE_SHA1}.tar.gz .;
          scp ${CIRCLE_SHA1}.tar.gz yudhistira.erlandinata@kawung.cs.ui.ac.id;
          ssh yudhistira.erlandinata@kawung.cs.ui.ac.id "scp ${CIRCLE_SHA1}.tar.gz enau.cs.ui.ac.id; ssh enau.cs.ui.ac.id 'source resetweb.sh; mv ${CIRCLE_SHA1}.tar.gz web/; cd web; tar -xvzf ${CIRCLE_SHA1}.tar.gz; python3 virtualenv env; source env/bin/activate; cd simbion; pip install -r requirements.txt; gunicorn -b 0.0.0.0:8020 simbion.wsgi & sleep 5;'";
        fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy
